#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./cstring.cpp ./sort.cpp 
PROG=sort
CFLAGS=-g -Wall -I. -Wwrite-strings
CC= g++
include /usr/lib/build/linux.prog.mk
